[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting = "CJQhZqq1X6EC2wE2sUYZAczqQSBvYs9DZGkrs8AQiRxB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
